services:
  backend:
    image: node:20
    container_name: check-pokemon-api
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    command: >
      sh -c "
        npm install &&
        npm run start
      "
